In [1]:

from sklearn.linear_model import LogisticRegression 
from sklearn.naive_bayes import GaussianNB


In [2]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier

In [3]:
from sklearn.svm import SVC


In [4]:
import pandas as pd
import xgboost as xgb
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


In [5]:
data=pd.read_csv('Dataset_UAV_8_12_24/datasetUAV8.csv')
print(data.head())

   807.41  535.57  161.72  182.65  170.32  861.78  494.26  221.65  143.26  \
0  161.72  182.65  807.41  535.57  170.32  861.78  494.26  221.65  143.26   
1  170.32  861.78  807.41  535.57  161.72  182.65  494.26  221.65  143.26   
2  494.26  221.65  807.41  535.57  161.72  182.65  170.32  861.78  143.26   
3  143.26  476.72  807.41  535.57  161.72  182.65  170.32  861.78  494.26   
4  449.64  653.16  807.41  535.57  161.72  182.65  170.32  861.78  494.26   

   476.72  449.64  653.16  744.14  858.3  840.38  229.76  3  
0  476.72  449.64  653.16  744.14  858.3  840.38  229.76  1  
1  476.72  449.64  653.16  744.14  858.3  840.38  229.76  3  
2  476.72  449.64  653.16  744.14  858.3  840.38  229.76  3  
3  221.65  449.64  653.16  744.14  858.3  840.38  229.76  2  
4  221.65  143.26  476.72  744.14  858.3  840.38  229.76  1  


In [6]:
import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
X=np.asarray(X)
y=np.asarray(y)

X_train, X_test, y_train, y_test=train_test_split(X,y,random_state=101,test_size=0.2)


In [7]:
print(X_train)
print(y_train)

[[886.7  242.19 154.64 ... 569.98 503.27 139.95]
 [146.73 204.47 561.66 ... 557.18 847.25 198.07]
 [167.11 801.2  838.14 ... 888.58 823.29 193.69]
 ...
 [214.26 808.84 849.91 ... 285.01 134.94 429.36]
 [532.35 360.83 489.5  ... 845.44 837.85 827.71]
 [264.66 879.66 843.37 ... 179.37 740.44 858.76]]
[2 1 3 ... 1 3 2]


In [8]:
GNB_model = GaussianNB()
SVC_model=svm.SVC()
LogisticR_model=LogisticRegression(random_state=101)  
KNN_model=KNeighborsClassifier(n_neighbors=5)
Dtree_model=DecisionTreeClassifier()
Random_model=RandomForestClassifier(n_estimators=10)
XGBOOST_model=xgb.XGBClassifier(objective='binary:logistic',seed=101)
GRADIENT_model=GradientBoostingClassifier(n_estimators=10, learning_rate=1.0,max_depth=1, random_state=101)
ADABOOST_model=AdaBoostClassifier(n_estimators=10,learning_rate=1)
BAGGINGBOOST_model = BaggingClassifier(base_estimator=SVC(),n_estimators=10, random_state=101)


In [9]:
GNB_model.fit(X_train,y_train)
SVC_model.fit(X_train,y_train)
LogisticR_model.fit(X_train,y_train)
KNN_model.fit(X_train,y_train)
Dtree_model.fit(X_train,y_train)
Random_model.fit(X_train,y_train)
XGBOOST_model.fit(X_train,y_train)
GRADIENT_model.fit(X_train,y_train)
ADABOOST_model.fit(X_train,y_train)
BAGGINGBOOST_model.fit(X_train,y_train)

C:\Users\GHJ\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[01:25:49] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


BaggingClassifier(base_estimator=SVC(), random_state=101)

In [10]:
GNB_prediction=GNB_model.predict(X_test)
SVC_prediction=SVC_model.predict(X_test)
LogisticR_prediction=LogisticR_model.predict(X_test)
KNN_prediction=KNN_model.predict(X_test)
Dtree_prediction=Dtree_model.predict(X_test)
Random_prediction=Random_model.predict(X_test)
XGBOOST_prediction=XGBOOST_model.predict(X_test)
GRADIENT_prediction=GRADIENT_model.predict(X_test)
ADABOOST_prediction=ADABOOST_model.predict(X_test)
BAGGINGBOOST_prediction=BAGGINGBOOST_model.predict(X_test)

In [11]:
print(accuracy_score(GNB_prediction,y_test))
print(accuracy_score(SVC_prediction,y_test))
print(accuracy_score(LogisticR_prediction,y_test))
print(accuracy_score(KNN_prediction,y_test))
print(accuracy_score(Dtree_prediction,y_test))
print(accuracy_score(Random_prediction,y_test))
print(accuracy_score(XGBOOST_prediction,y_test))
print(accuracy_score(GRADIENT_prediction,y_test))
print(accuracy_score(ADABOOST_prediction,y_test))
print(accuracy_score(BAGGINGBOOST_prediction,y_test))



print(confusion_matrix(GNB_prediction,y_test))
print(confusion_matrix(SVC_prediction,y_test))
print(confusion_matrix(LogisticR_prediction,y_test))
print(confusion_matrix(KNN_prediction,y_test))
print(confusion_matrix(Dtree_prediction,y_test))
print(confusion_matrix(Random_prediction,y_test))
print(confusion_matrix(XGBOOST_prediction,y_test))
print(confusion_matrix(GRADIENT_prediction,y_test))
print(confusion_matrix(ADABOOST_prediction,y_test))
print(confusion_matrix(BAGGINGBOOST_prediction,y_test))



print(classification_report(GNB_prediction,y_test)) 
print(classification_report(SVC_prediction,y_test))
print(classification_report(LogisticR_prediction,y_test))
print(classification_report(KNN_prediction,y_test))
print(classification_report(Dtree_prediction,y_test))
print(classification_report(Random_prediction,y_test))
print(classification_report(XGBOOST_prediction,y_test))
print(classification_report(GRADIENT_prediction,y_test))
print(classification_report(ADABOOST_prediction,y_test))
print(classification_report(BAGGINGBOOST_prediction,y_test))

      



0.400125
0.6854759615384616
0.39065865384615384
0.7366730769230769
0.6824134615384615
0.7457355769230769
0.7496057692307693
0.43623076923076926
0.41215865384615386
0.6861682692307692
[[41381 28269 26565]
 [14894 18492 15631]
 [17356 22059 23353]]
[[62945 10978  9536]
 [ 4892 37013 13392]
 [ 5794 20829 42621]]
[[42828 31609 29707]
 [15663 17242 14655]
 [15140 19969 21187]]
[[65824  7224  6994]
 [ 4705 46265 17416]
 [ 3102 15331 41139]]
[[59356  7067  6681]
 [ 7361 42778 19060]
 [ 6914 18975 39808]]
[[65345  6746  6421]
 [ 4538 49246 18606]
 [ 3748 12828 40522]]
[[64960  7060  7064]
 [ 4766 46269 13796]
 [ 3905 15491 44689]]
[[40574 22217 23459]
 [16473 26728 18656]
 [16584 19875 23434]]
[[40540 25218 26850]
 [15298 25036 18546]
 [17793 18566 20153]]
[[63140 11046  9649]
 [ 4854 37559 13876]
 [ 5637 20215 42024]]
              precision    recall  f1-score   support

           1       0.56      0.43      0.49     96215
           2       0.27      0.38      0.31     49017
           3  