In [1]:

from sklearn.linear_model import LogisticRegression 


In [2]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier

In [3]:
from sklearn.svm import SVC


In [4]:
import pandas as pd
import xgboost as xgb
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


In [5]:
data=pd.read_csv('Dataset_UAV_8_12_24/datasetUAV5.csv')
print(data.head())

   730.34  224.79  197.86  799.64  842.04  724.97  237.79  247.96  507.28  \
0  197.86  799.64  730.34  224.79  842.04  724.97  237.79  247.96  507.28   
1  842.04  724.97  730.34  224.79  197.86  799.64  237.79  247.96  507.28   
2  237.79  247.96  730.34  224.79  197.86  799.64  842.04  724.97  507.28   
3  507.28  689.68  730.34  224.79  197.86  799.64  842.04  724.97  237.79   
4  495.39  312.55  240.27  755.28  778.13  741.41  845.54  158.47  197.07   

   689.68  2  
0  689.68  2  
1  689.68  1  
2  689.68  1  
3  247.96  3  
4  259.46  2  


In [6]:
import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split
X=data.iloc[:487500,[9,8]].values
y=data.iloc[:487500,-1].values
X=np.asarray(X)
y=np.asarray(y)

X_train, X_test, y_train, y_test=train_test_split(X,y,random_state=101,test_size=0.2)


In [7]:
print(X_train)
print(y_train)

[[513.66 464.29]
 [334.19 466.74]
 [469.61 475.26]
 ...
 [733.93 153.7 ]
 [213.47 834.88]
 [519.07 673.69]]
[1 1 1 ... 2 2 3]


In [8]:
SVC_model=svm.SVC()
LogisticR_model=LogisticRegression(random_state=101)  
KNN_model=KNeighborsClassifier(n_neighbors=5)
Dtree_model=DecisionTreeClassifier()
Random_model=RandomForestClassifier(n_estimators=10)
XGBOOST_model=xgb.XGBClassifier(objective='binary:logistic',seed=101)
GRADIENT_model=GradientBoostingClassifier(n_estimators=10, learning_rate=1.0,max_depth=1, random_state=101)
ADABOOST_model=AdaBoostClassifier(n_estimators=10,learning_rate=1)
BAGGINGBOOST_model = BaggingClassifier(base_estimator=SVC(),n_estimators=10, random_state=101)


In [9]:
SVC_model.fit(X_train,y_train)
LogisticR_model.fit(X_train,y_train)
KNN_model.fit(X_train,y_train)
Dtree_model.fit(X_train,y_train)
Random_model.fit(X_train,y_train)
XGBOOST_model.fit(X_train,y_train)
GRADIENT_model.fit(X_train,y_train)
ADABOOST_model.fit(X_train,y_train)
BAGGINGBOOST_model.fit(X_train,y_train)

C:\Users\GHJ\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[17:01:34] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


BaggingClassifier(base_estimator=SVC(), random_state=101)

In [10]:
SVC_prediction=SVC_model.predict(X_test)
LogisticR_prediction=LogisticR_model.predict(X_test)
KNN_prediction=KNN_model.predict(X_test)
Dtree_prediction=Dtree_model.predict(X_test)
Random_prediction=Random_model.predict(X_test)
XGBOOST_prediction=XGBOOST_model.predict(X_test)
GRADIENT_prediction=GRADIENT_model.predict(X_test)
ADABOOST_prediction=ADABOOST_model.predict(X_test)
BAGGINGBOOST_prediction=BAGGINGBOOST_model.predict(X_test)

In [11]:
print(accuracy_score(SVC_prediction,y_test))
print(accuracy_score(LogisticR_prediction,y_test))
print(accuracy_score(KNN_prediction,y_test))
print(accuracy_score(Dtree_prediction,y_test))
print(accuracy_score(Random_prediction,y_test))
print(accuracy_score(XGBOOST_prediction,y_test))
print(accuracy_score(GRADIENT_prediction,y_test))
print(accuracy_score(ADABOOST_prediction,y_test))
print(accuracy_score(BAGGINGBOOST_prediction,y_test))



print(confusion_matrix(SVC_prediction,y_test))
print(confusion_matrix(LogisticR_prediction,y_test))
print(confusion_matrix(KNN_prediction,y_test))
print(confusion_matrix(Dtree_prediction,y_test))
print(confusion_matrix(Random_prediction,y_test))
print(confusion_matrix(XGBOOST_prediction,y_test))
print(confusion_matrix(GRADIENT_prediction,y_test))
print(confusion_matrix(ADABOOST_prediction,y_test))
print(confusion_matrix(BAGGINGBOOST_prediction,y_test))



 
print(classification_report(SVC_prediction,y_test))
print(classification_report(LogisticR_prediction,y_test))
print(classification_report(KNN_prediction,y_test))
print(classification_report(Dtree_prediction,y_test))
print(classification_report(Random_prediction,y_test))
print(classification_report(XGBOOST_prediction,y_test))
print(classification_report(GRADIENT_prediction,y_test))
print(classification_report(ADABOOST_prediction,y_test))
print(classification_report(BAGGINGBOOST_prediction,y_test))

      



0.5057948717948718
0.4277846153846154
0.33205128205128204
0.2602769230769231
0.27524102564102565
0.48584615384615387
0.4957128205128205
0.4861846153846154
0.505374358974359
[[31338  5763 27358]
 [ 6411 16223  6789]
 [ 1232   632  1754]]
[[30309 17058 24759]
 [  619  1434  1176]
 [ 8053  4126  9966]]
[[13556  8751 23317]
 [ 6261 11641  5406]
 [19164  2226  7178]]
[[14523  9752 31184]
 [ 5110  9084  2947]
 [19348  3782  1770]]
[[ 8529  6849 24405]
 [ 6676 11580  4769]
 [23776  4189  6727]]
[[24318  6656 21624]
 [ 5139 14328  5553]
 [ 9524  1634  8724]]
[[26487  5375 23238]
 [ 7401 16587  7405]
 [ 5093   656  5258]]
[[30640  5673 27633]
 [ 6323 13192  4697]
 [ 2018  3753  3571]]
[[31239  5788 27284]
 [ 6381 16210  6792]
 [ 1361   620  1825]]
              precision    recall  f1-score   support

           1       0.80      0.49      0.61     64459
           2       0.72      0.55      0.62     29423
           3       0.05      0.48      0.09      3618

    accuracy                     