In [19]:
from sklearn.linear_model import LogisticRegression


In [20]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm

In [21]:
from sklearn.svm import SVC

In [22]:
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


In [23]:
data=pd.read_csv('Dataset_UAV_8_12_24/datasetUAV12.csv')
print(data.head())

   857.35   162.7   111.6  900.6  888.5  860.18  198.61  175.24  499.25  \
0  111.60  900.60  857.35  162.7  888.5  860.18  198.61  175.24  499.25   
1  888.50  860.18  857.35  162.7  111.6  900.60  198.61  175.24  499.25   
2  198.61  175.24  857.35  162.7  111.6  900.60  888.50  860.18  499.25   
3  499.25  571.10  857.35  162.7  111.6  900.60  888.50  860.18  198.61   
4  864.29  551.18  857.35  162.7  111.6  900.60  888.50  860.18  198.61   

    571.1  ...  681.92  372.08  858.96  636.8  375.09  233.13  409.53  624.02  \
0  571.10  ...  681.92  372.08  858.96  636.8  375.09  233.13  409.53  624.02   
1  571.10  ...  681.92  372.08  858.96  636.8  375.09  233.13  409.53  624.02   
2  571.10  ...  681.92  372.08  858.96  636.8  375.09  233.13  409.53  624.02   
3  175.24  ...  681.92  372.08  858.96  636.8  375.09  233.13  409.53  624.02   
4  175.24  ...  681.92  372.08  858.96  636.8  375.09  233.13  409.53  624.02   

   815.97  2  
0  815.97  1  
1  815.97  1  
2  815.97  1  
3 

In [24]:
import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split
X=data.iloc[:500000,:23].values
y=data.iloc[:500000,-1].values
X=np.asarray(X)
y=np.asarray(y)

X_train, X_test, y_train, y_test=train_test_split(X,y,random_state=101,test_size=0.2)


In [25]:
print(X_train)
print(y_train)

[[262.99 394.22 125.82 ... 673.84 781.52 158.55]
 [497.88 896.93 388.86 ... 436.   648.58 629.02]
 [873.27 834.69 904.19 ... 320.69 803.84 745.8 ]
 ...
 [913.89 170.37 168.35 ... 389.35 626.28 672.11]
 [516.76 402.26 422.52 ... 144.61 367.6  863.16]
 [601.76 874.4  429.68 ... 309.01 114.98 773.18]]
[3 3 3 ... 2 1 3]


In [26]:
SVC_model=svm.SVC()
KNN_model=KNeighborsClassifier(n_neighbors=5)

In [ ]:
SVC_model.fit(X_train,y_train)
KNN_model.fit(X_train,y_train)

In [ ]:
SVC_prediction=SVC_model.predict(X_test)
KNN_prediction=KNN_model.predict(X_test)

In [ ]:
print(accuracy_score(SVC_prediction,y_test))
print(accuracy_score(KNN_prediction,y_test))
      
print(confusion_matrix(SVC_prediction,y_test))
print(confusion_matrix(KNN_prediction,y_test))
 
print(classification_report(SVC_prediction,y_test))
print(classification_report(KNN_prediction,y_test))
